name = "tennis-strings-site"
compatibility_date = "2024-01-01"
main = ".svelte-kit/cloudflare/_worker.js"

[build]
command = "npm run build"

[assets]
directory = ".svelte-kit/cloudflare/_app"
binding = "ASSETS"